// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsFes-Qn1IiV5PwMoJM1MfHEGT7FAHVSY',
    appId: '1:994231389706:web:8cdb2e5bc3078e4eba59f3',
    messagingSenderId: '994231389706',
    projectId: 'guard-ab0d3',
    authDomain: 'guard-ab0d3.firebaseapp.com',
    storageBucket: 'guard-ab0d3.firebasestorage.app',
    measurementId: 'G-PRXL7BRH7V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqfW0I5tS6g9031TIQlu2P3qA9dDbKBoo',
    appId: '1:994231389706:android:3b84631c845d688eba59f3',
    messagingSenderId: '994231389706',
    projectId: 'guard-ab0d3',
    storageBucket: 'guard-ab0d3.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwNu1TVIiodYKP1EaTqZ4649R6oFr6AkQ',
    appId: '1:994231389706:ios:bed99086c42fb9a9ba59f3',
    messagingSenderId: '994231389706',
    projectId: 'guard-ab0d3',
    storageBucket: 'guard-ab0d3.firebasestorage.app',
    iosBundleId: 'com.binarypulse.amarguard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsFes-Qn1IiV5PwMoJM1MfHEGT7FAHVSY',
    appId: '1:994231389706:web:185a98ed88aed445ba59f3',
    messagingSenderId: '994231389706',
    projectId: 'guard-ab0d3',
    authDomain: 'guard-ab0d3.firebaseapp.com',
    storageBucket: 'guard-ab0d3.firebasestorage.app',
    measurementId: 'G-3VV8B5GKDR',
  );
}
